// frontend/src/components/NavBar.vue
<script setup>
import { storeToRefs } from "pinia";
import { useCounterStore } from "../store/user/userStore";
import { useRoutes } from "../composables/useRoutes";

const store = useCounterStore();
const { isLogged } = storeToRefs(store);
const { goToRegisterPage, goToHomePage } = useRoutes();
</script>

<template>
  <nav
    class="flex bg-amber-600 text-white justify-between fixed w-screen px-10 py-5"
  >
    <div @click="goToHomePage" class="font-extrabold cursor-pointer">Logo</div>
    <div v-if="isLogged" class="cursor-pointer">Mis notas</div>
    <div
      @click="goToRegisterPage"
      class="cursor-pointer font-bold text-[1.2em]"
      v-else
    >
      Iniciar sesion
    </div>
  </nav>
</template>

// frontend/src/components/NavBar.tsx
import React from "react";
import useUserStore from "../store/user/userStore";
import { Link } from "react-router-dom";

const NavBar = () => {
  const { logged } = useUserStore();

  return (
    <nav className="flex justify-between fixed w-full bg-blue-500 px-5 py-2 text-white">
      <Link to={'/'} className="text-[1.2rem] font-bold">NoteAPP</Link>
      <div>
        {logged ? (
          <Link to={"/notes"}>Mis notas.</Link>
        ) : (
          <div className="flex gap-5">
            <Link to={"/register"}>Registrarme</Link>
            <Link to={"/login"}>Iniciar sesion</Link>
          </div>
        )}
      </div>
    </nav>
  );
};

export default NavBar;
